from CustomEnv.mujoco.ant import AntEnv
from CustomEnv.mujoco.half_cheetah import HalfCheetahEnv
from CustomEnv.mujoco.hopper import HopperEnv
from CustomEnv.mujoco.walker2d import Walker2dEnv
from CustomEnv.mujoco.humanoid import HumanoidEnv
from CustomEnv.mujoco.inverted_pendulum import InvertedPendulumEnv
from CustomEnv.mujoco.inverted_double_pendulum import InvertedDoublePendulumEnv
from CustomEnv.mujoco.reacher import ReacherEnv
from CustomEnv.mujoco.swimmer import SwimmerEnv
from CustomEnv.mujoco.humanoidstandup import HumanoidStandupEnv
from CustomEnv.mujoco.pusher import PusherEnv
from CustomEnv.mujoco.thrower import ThrowerEnv
from CustomEnv.mujoco.striker import StrikerEnv
